/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.spire.doc.FileFormat;
import com.spire.doc.Section;
import com.spire.doc.documents.Paragraph;
import com.spire.doc.documents.ParagraphStyle;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jocma
 */
public class GeneradorScripts extends javax.swing.JFrame {

    fondoBl fondo = new fondoBl();
    DefaultTableModel model;
    int cont=0;
    String content = ""; 
    public GeneradorScripts() {
       
        
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
        model  = (DefaultTableModel) tbl_campos.getModel();

        cb_db.addItem("Oracle");
        cb_db.addItem("PostgresSQL");
        cb_db.addItem("MySQL");
        cb_db.addItem("SQLServer");
        
        cb_query.addItem("Select");
        cb_query.addItem("Insert");
        cb_query.addItem("Update");
        cb_query.addItem("Delete");
        cb_query.addItem("Create BD");
        cb_query.addItem("Create Table");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondoBl();
        jPanel2 = new fondoP();
        cmd_regresar = new javax.swing.JButton();
        lbl_titulo = new javax.swing.JLabel();
        cb_db = new javax.swing.JComboBox<>();
        lbl_db = new javax.swing.JLabel();
        lbl_query = new javax.swing.JLabel();
        cb_query = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_campos = new javax.swing.JTable();
        cmd_descargar = new javax.swing.JButton();
        cmd_agregar = new javax.swing.JButton();
        cmd_eliminar = new javax.swing.JButton();
        cmd_limpiar = new javax.swing.JButton();
        txtNameTable = new javax.swing.JTextField();
        nameTable222 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        cmd_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar_32.png"))); // NOI18N
        cmd_regresar.setContentAreaFilled(false);
        cmd_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cmd_regresar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cmd_regresar, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );

        lbl_titulo.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(51, 51, 51));
        lbl_titulo.setText("Generador de scripts");

        cb_db.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        lbl_db.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lbl_db.setForeground(new java.awt.Color(102, 102, 102));
        lbl_db.setText("Motor BD");

        lbl_query.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        lbl_query.setForeground(new java.awt.Color(102, 102, 102));
        lbl_query.setText("Tipo de Query");

        cb_query.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        cb_query.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbl_campos.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        tbl_campos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Script"
            }
        ));
        tbl_campos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_camposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_campos);

        cmd_descargar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        cmd_descargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/generar_24.png"))); // NOI18N
        cmd_descargar.setText("Descargar");
        cmd_descargar.setContentAreaFilled(false);
        cmd_descargar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmd_descargar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/generar_32.png"))); // NOI18N
        cmd_descargar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/generar_24.png"))); // NOI18N
        cmd_descargar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmd_descargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_descargarActionPerformed(evt);
            }
        });

        cmd_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas_24.png"))); // NOI18N
        cmd_agregar.setContentAreaFilled(false);
        cmd_agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas_32.png"))); // NOI18N
        cmd_agregar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mas_24.png"))); // NOI18N
        cmd_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_agregarActionPerformed(evt);
            }
        });

        cmd_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menos_24.png"))); // NOI18N
        cmd_eliminar.setContentAreaFilled(false);
        cmd_eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menos_32.png"))); // NOI18N
        cmd_eliminar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menos_24.png"))); // NOI18N
        cmd_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_eliminarActionPerformed(evt);
            }
        });

        cmd_limpiar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        cmd_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar_24.png"))); // NOI18N
        cmd_limpiar.setContentAreaFilled(false);
        cmd_limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmd_limpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar_32.png"))); // NOI18N
        cmd_limpiar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Limpiar_24.png"))); // NOI18N
        cmd_limpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmd_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_limpiarActionPerformed(evt);
            }
        });

        txtNameTable.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N

        nameTable222.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        nameTable222.setForeground(new java.awt.Color(102, 102, 102));
        nameTable222.setText("Nombre tabla:");

        txtContent.setColumns(20);
        txtContent.setRows(5);
        jScrollPane2.setViewportView(txtContent);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(117, 117, 117))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(cmd_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmd_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cmd_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(nameTable222)
                .addGap(18, 18, 18)
                .addComponent(txtNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lbl_titulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cb_db, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(lbl_db)))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lbl_query))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cb_query, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                                .addComponent(cmd_descargar)))))
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbl_titulo)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_query, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_db))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_query, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameTable222)
                                    .addComponent(txtNameTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(cmd_descargar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmd_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmd_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmd_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel1)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_agregarActionPerformed
       
        if(txtNameTable.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Warning:Nombre de tabla Vacio");
        }
        else {
            
        
        
        Object datos[] = new Object[1];
       //String nblanco = "";
       /*if(cb_query.getSelectedItem().equals("Insert")){
           datos[0]= "INSERT INTO "+txtNameTable.getText()+" VALUES(<data>);";
       }else if(cb_query.getSelectedItem().equals("Update")){
           datos[0] = "UPDATE "+txtNameTable.getText()+" SET <data> WHERE <condition> ;";
       }else if(cb_query.getSelectedItem().equals("Select")){
           datos[0] = "SELECT * FROM "+txtNameTable.getText()+";";
       }else if(cb_query.getSelectedItem().equals("Delete")){
           datos[0] = "DELETE FROM "+txtNameTable.getText()+" WHERE <condition>;";
       }else if(cb_query.getSelectedItem().equals("Create BD")){
           datos[0] = "CREATE DATABASE "+txtNameTable.getText()+";";
       }else if(cb_query.getSelectedItem().equals("Create Table")){
           datos[0] = "CREATE TABLE "+txtNameTable.getText()+"( <atributes> );";
       }*/
       if(cb_query.getSelectedItem().equals("Insert")){
           datos[0] = content+"INSERT INTO "+txtNameTable.getText()+"(<Column Names>)"+" VALUES(<data>);";
           
       }else if(cb_query.getSelectedItem().equals("Update")){
           datos[0] = "UPDATE "+txtNameTable.getText()+" SET <data> WHERE <condition> ;";
       }else if(cb_query.getSelectedItem().equals("Select")){
           datos[0] = "SELECT * FROM "+txtNameTable.getText()+";";
       }else if(cb_query.getSelectedItem().equals("Delete")){
           datos[0] = "DELETE FROM "+txtNameTable.getText()+" WHERE <condition>;";
       }else if(cb_query.getSelectedItem().equals("Create BD")){
           datos[0] = "CREATE DATABASE "+txtNameTable.getText()+";";
       }else if(cb_query.getSelectedItem().equals("Create Table")){
           datos[0] = "CREATE TABLE "+txtNameTable.getText()+"( <atributes> );";
       }
       
       //datos[0] = "INSERT INTO "+txtNameTable.getText()+" VALUES(<data>);";
       model.addRow(datos);
        }
    }//GEN-LAST:event_cmd_agregarActionPerformed

    private void cmd_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_eliminarActionPerformed
        if (model.getRowCount()>0){
                
            model.removeRow(0);
        }
    }//GEN-LAST:event_cmd_eliminarActionPerformed

    private void cmd_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_regresarActionPerformed
        Menu mn = new Menu();
        this.dispose();
        mn.setVisible(true);
    }//GEN-LAST:event_cmd_regresarActionPerformed

    private void cmd_descargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_descargarActionPerformed
        // TODO add your handling code here:
        //cont = cont+1;
        //model.setValueAt("INSERT INTO "+txtNameTable.getText()+" VALUES(<data>);", 1, 0);
        //tbl_campos.setTableHeader(tableHeader);

        

        if(txtContent.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Warning: Script en blanco");
        }else{
            
            String ruta = "";
        JFileChooser chooser = new JFileChooser();

        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            ruta = chooser.getSelectedFile().getAbsolutePath();
        }

        com.spire.doc.Document documento = new com.spire.doc.Document();

        Section section = documento.addSection();

        Paragraph parrafo_1 = section.addParagraph();
        parrafo_1.appendText(txtContent.getText());
        
        ParagraphStyle estilo = new ParagraphStyle(documento);
        
        estilo.setName("estiloNormal");

        
        documento.getStyles().add(estilo);
        parrafo_1.applyStyle("estiloNormal");
        
        // Aquí recuerda cambiar la ruta de tu imagen
        //File imagen = new File("C:\\Users\\osvaldo\\Documents\\NetBeansProjects\\GenerarArchivoWord\\src\\iconos\\Logo.png");

                

        documento.saveToFile(ruta + ".sql", FileFormat.Txt);
        }
        
    }//GEN-LAST:event_cmd_descargarActionPerformed

    private void cmd_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_limpiarActionPerformed
        // TODO add your handling code here:
        txtContent.setText("");
        txtNameTable.setText("");
        
        
    }//GEN-LAST:event_cmd_limpiarActionPerformed

    private void tbl_camposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_camposMouseClicked

      
       String cadena = "";
       
       for (int i = 0 ; i<tbl_campos.getRowCount();i++)
       {
       cadena = cadena +  String.valueOf(tbl_campos.getValueAt(i, 0)+"\n\n");
       }
       
       txtContent.setText(cadena);
       
    }//GEN-LAST:event_tbl_camposMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneradorScripts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneradorScripts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneradorScripts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneradorScripts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneradorScripts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_db;
    private javax.swing.JComboBox<String> cb_query;
    private javax.swing.JButton cmd_agregar;
    private javax.swing.JButton cmd_descargar;
    private javax.swing.JButton cmd_eliminar;
    private javax.swing.JButton cmd_limpiar;
    private javax.swing.JButton cmd_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_db;
    private javax.swing.JLabel lbl_query;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel nameTable222;
    private javax.swing.JTable tbl_campos;
    private javax.swing.JTextArea txtContent;
    private javax.swing.JTextField txtNameTable;
    // End of variables declaration//GEN-END:variables
class fondoBl extends JPanel
            
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
          imagen = new ImageIcon(getClass().getResource("/Imagenes/FondoB.jpg")).getImage();
          g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
          setOpaque(false);
          
          super.paint(g);
        }
    }
    
    
    class fondoP extends JPanel
            
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
          imagen = new ImageIcon(getClass().getResource("/Imagenes/FondoN.jpg")).getImage();
          g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
          setOpaque(false);
          
          super.paint(g);
        }
    }

 


}
