/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author jocma
 */
public class Menu extends javax.swing.JFrame {

   fondoBl fondo =  new fondoBl();
   
    public Menu() {
        this.setContentPane(fondo);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondoBl();
        jPanel2 = new fondoP();
        lbl_titulo = new javax.swing.JLabel();
        cmd_gscripts = new javax.swing.JButton();
        cmd_backup = new javax.swing.JButton();
        cmd_edd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        lbl_titulo.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(102, 102, 102));
        lbl_titulo.setText("ManBD");

        cmd_gscripts.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        cmd_gscripts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gscripts_32.png"))); // NOI18N
        cmd_gscripts.setText("Generador Scripts");
        cmd_gscripts.setContentAreaFilled(false);
        cmd_gscripts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmd_gscripts.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gscripts_32.png"))); // NOI18N
        cmd_gscripts.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gscripts_48.png"))); // NOI18N
        cmd_gscripts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmd_gscripts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_gscriptsActionPerformed(evt);
            }
        });

        cmd_backup.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        cmd_backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backup_32.png"))); // NOI18N
        cmd_backup.setText("Backup");
        cmd_backup.setContentAreaFilled(false);
        cmd_backup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmd_backup.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backup_48.png"))); // NOI18N
        cmd_backup.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/backup_32.png"))); // NOI18N
        cmd_backup.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmd_backup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_backupActionPerformed(evt);
            }
        });

        cmd_edd.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        cmd_edd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edd_32.png"))); // NOI18N
        cmd_edd.setText("Estructura de instrucciones");
        cmd_edd.setContentAreaFilled(false);
        cmd_edd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmd_edd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edd_48.png"))); // NOI18N
        cmd_edd.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edd_32.png"))); // NOI18N
        cmd_edd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmd_edd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_eddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmd_gscripts, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmd_backup, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 119, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cmd_edd)
                                .addGap(108, 108, 108))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_titulo)
                                .addGap(158, 158, 158))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(cmd_gscripts, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(cmd_edd, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(cmd_backup, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_backupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_backupActionPerformed
        Backups bk =  new Backups();
        this.dispose();
        bk.setVisible(true);
    }//GEN-LAST:event_cmd_backupActionPerformed

    private void cmd_gscriptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_gscriptsActionPerformed
        
        GeneradorScripts gs = new GeneradorScripts();
        this.dispose();
        gs.setVisible(true);
    }//GEN-LAST:event_cmd_gscriptsActionPerformed

    private void cmd_eddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_eddActionPerformed
        GeneradorStruct gstruct = new GeneradorStruct();
        this.dispose();
        gstruct.setVisible(true);
    }//GEN-LAST:event_cmd_eddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_backup;
    private javax.swing.JButton cmd_edd;
    private javax.swing.JButton cmd_gscripts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables

    class fondoBl extends JPanel
            
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
          imagen = new ImageIcon(getClass().getResource("/Imagenes/FondoB.jpg")).getImage();
          g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
          setOpaque(false);
          
          super.paint(g);
        }
    }
    
    
    class fondoP extends JPanel
            
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g)
        {
          imagen = new ImageIcon(getClass().getResource("/Imagenes/FondoN.jpg")).getImage();
          g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
          setOpaque(false);
          
          super.paint(g);
        }
    }

}
